spring:
  application:
    name: api-gateway # Identifier of this application

server:
  port: 2222

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of the eureka server for registration
            
zuul:
  ignoredPatterns: /login/** # The login path is served by the api-gateway directly
  ignored-services: "*"
  routes: # Forwardings of requests
    dummy-service:
      path: /**
      service-id: dummy-service
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: false # Forward the request all together with the auth path
      sensitive-headers: Cookie, Set-Cookie # Avoid to send internal cookies to external entities